# pancharts —k_vm 特征矩阵可视化

基于pyecharts的可视化工具，配置语法与原生的echarts保持一致，完全兼容pandas的数据结构

老师自己开发！

https://github.com/wisherg/pancharts

https://echarts.apache.org/zh/api.html#echarts

### 安装

pip install pancharts -i https://mirrors.aliyun.com/pypi/simple/

### 更新

* 更新前请先保存你的配置文件！

pip install --upgrade pancharts -i https://mirrors.aliyun.com/pypi/simple/

In [38]:
import numpy as np
import pandas as pd
from pancharts import echat,pchat,k2_nv,k2_nv,k_v,km_nv,Pancharts,create_visual_map
import pancharts as pc

In [2]:
pc.__version__

'0.1.4'

## 内置agent的使用与全局配置

In [3]:
from pancharts.utils import get_config_file_path

config_path = get_config_file_path()
print(config_path)

d:\soft\anaconda\Lib\site-packages\pancharts\chart_config.py

## 多列数值型数据（k_vm）可视化

In [3]:
print(pc.k_vm.__doc__)

用于可视化pandas中的单列索引、多列数值型数据的DataFrame。

主要功能：
    - 自动将pandas DataFrame转换为ECharts可接受的数据格式
    - 支持通过config参数传入额外的图表配置，与默认配置合并
    - 提供多维数据可视化的图表类型
    - 支持灵活的数据编码方式（rect_plot方法）
    - 支持数据的可视化映射（vmap_size和vmap_color方法）

支持的图表类型：
    - parallel: 平行坐标图
    - radar: 雷达图
    - rect_plot: 灵活数据编码方式，支持多种二维图表

参数：
    data: pandas DataFrame - 要可视化的数据，需具有单列索引和多列数值

用法示例：
    from pancharts import k_vm
    import pandas as pd
    import numpy as np

    # 创建数据
    data = pd.DataFrame(
        np.random.rand(5, 4),
        columns=['a', 'b', 'c', 'd'],
        index=['x', 'y', 'z', 'w', 'v']
    )
    chart = k_vm(data).parallel()
    chart.render()

In [4]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=['a','b','c'],columns=['x','y','z'])
vm0=pc.k_vm(df)
vm0.radar().render_notebook()

In [5]:
df

   x  y  z
a  1  2  3
b  4  5  6
c  7  8  9

In [6]:
df=pd.DataFrame([[1,2,3,'a'],[4,5,6,'b'],[7,8,9,'c']],index=['a','b','c'],columns=['x','y','z','w'])
vm0=pc.k_vm(df)
vm0.parallel().render_notebook()

## classwork 1

多列数据框的可视化

1. 求不同店铺的统计指标（price_mean, gmv_sum, gmv_mean, sales_mean, sales_sum, size）
2. 可视化不同店铺的统计指标

In [8]:
a=pd.read_csv(r"e:\shoes.csv")
a["sales"]=a.sales.str.replace("人付款","").astype(int)
a["gmv"]=a.sales*a.price

In [9]:
nick_tz=a.groupby("nick").agg(price_mean=("price", "mean"), 
                      gmv_sum=("gmv", "sum"),
                      gmv_mean=("gmv", "mean"),
                      sales_mean=("sales", "mean"),
                      sales_sum=("sales", "sum"),
                      size=("nick", "size"),
                      ).sort_values(by="gmv_sum", ascending=False)
nick_tz

             price_mean    gmv_sum      gmv_mean  sales_mean  sales_sum  size
nick
意尔康皮鞋旗舰店     485.712803  3558446.0  12312.961938   47.833910      13824   289
意尔康男鞋旗舰店     680.812081   792685.0   5320.033557   17.953020       2675   149
意尔康品牌店       271.461538   114452.0   1760.800000    7.661538        498    65
乙方乙方88888    164.666667    88144.0   9793.777778   60.333333        543     9
吸引力xl        152.000000    43870.0   8774.000000   59.000000        295     5
...                 ...        ...           ...         ...        ...   ...
cf新款更新       173.000000        0.0      0.000000    0.000000          0     2
chenyouyin2  388.000000        0.0      0.000000    0.000000          0     1
闺蜜衣橱gqx      508.000000        0.0      0.000000    0.000000          0     1
36233我也是醉了   540.833333        0.0      0.000000    0.000000          0     3
龙凤吉祥4249     158.666667        0.0      0.000000    0.000000          0     3

[482 rows x 6 columns]

In [20]:
p4=nick_tz.head(5)
p4_vm=pc.k_vm(p4)

In [21]:
tz0=p4_vm.radar()
tz0.render_notebook()

In [22]:
tz0.patch_option("雷达图的里面增加阴影，透明度为0.5",verbose=True)

AI Model Response:
{
    "series": [{
        "type": "radar",
        "areaStyle": {
            "opacity": 0.5
        }
    }]
}

In [23]:
tz0.render_notebook()

In [18]:
tz1=p4_vm.parallel()
tz1.render_notebook()

In [19]:
tz1.patch_option("并行图的每条线有不同的颜色",verbose=True)
tz1.render_notebook()

AI Model Response:
{
    "series": [{
        "type": "parallel",
        "lineStyle": {
            "width": 4
        },
        "data": [[485.7128027681661, 3558446.0, 12312.961937716263, 47.83391003460208, 13824.0, 289.0], [680.8120805369127, 792685.0, 5320.03355704698, 17.953020134228186, 2675.0, 149.0], [271.46153846153845, 114452.0, 1760.8, 7.661538461538462, 498.0, 65.0], [164.66666666666666, 88144.0, 9793.777777777777, 60.333333333333336, 543.0, 9.0], [152.0, 43870.0, 8774.0, 59.0, 295.0, 5.0]],
        "lineStyle": {
            "color": "JsCode:function(params) { return ['#d87c7c', '#919e8b', '#d7ab82', '#6e7074', '#61a0a8'][params.dataIndex % 5]; }"
        }
    }]
}

## rect_plot 基于dataset的直角坐标系图可视化

* 支持bar、line、scatter、effectScatter等类型的直角坐标系图可视化

* 支持一套坐标系下的多数据叠加

In [24]:
df

   x  y  z  w
a  1  2  3  a
b  4  5  6  b
c  7  8  9  c

In [25]:
vm1=pc.k_vm(df)

In [26]:
vm1.rect_plot("bar",2,1).render_notebook()#对于数据框来说，索引是第0列，其他列从1顺序编号

In [27]:
vm1.rect_plot("line",0,[1,2,3]).render_notebook()

In [28]:
vm1.rect_plot("effectScatter",0,[1,2]).render_notebook()

### classwork2

* 比较前五店铺的sales_mean与size

* 比较"意尔康皮鞋旗舰店","意尔康男鞋旗舰店"两个店铺的'info.鞋面材质'商品数量

* 用散点图研究销量前100店铺各个维度的关系

In [29]:
nick_tz.head(5)

           price_mean    gmv_sum      gmv_mean  sales_mean  sales_sum  size
nick
意尔康皮鞋旗舰店   485.712803  3558446.0  12312.961938   47.833910      13824   289
意尔康男鞋旗舰店   680.812081   792685.0   5320.033557   17.953020       2675   149
意尔康品牌店     271.461538   114452.0   1760.800000    7.661538        498    65
乙方乙方88888  164.666667    88144.0   9793.777778   60.333333        543     9
吸引力xl      152.000000    43870.0   8774.000000   59.000000        295     5

In [30]:
p4_vm.rect_plot("bar",0,[4,6]).render_notebook()

In [31]:
t1=a.groupby(["nick","info.鞋面材质"]).size()

In [32]:
t2=t1[["意尔康皮鞋旗舰店","意尔康男鞋旗舰店"]].unstack(level=0).fillna(0)
t2_kvm=pc.k_vm(t2)

In [33]:
t2

nick        意尔康皮鞋旗舰店  意尔康男鞋旗舰店
info.鞋面材质
多种材质拼接           8.0       7.0
头层牛皮（除牛反绒）     277.0     138.0
牛反绒              1.0       0.0
网布               1.0       1.0
鳄鱼皮              2.0       2.0
太空革              0.0       1.0

In [34]:
t2_kvm.rect_plot("bar",0,[1,2]).render_notebook()

In [35]:
t3=pc.k_vm(nick_tz.head(100))

In [36]:
t3.rect_plot("scatter",4,1).render_notebook()

## 数据与颜色大小的映射

In [43]:
print(create_visual_map.__doc__)

生成ECharts的visualMap映射配置

参数:
    dataframe: pd.DataFrame - 输入的数据框
    map_types: str | List[str] - 映射类型，可选值为 "color", "opacity", "symbolSize", "symbol", "lightness", "saturation"
    columns: int | List[int] - 映射的数据框列索引（基于顺序索引），可以是一列或多列

返回:
    List[dict] - visualMap配置列表，每个元素对应一个visualMap配置

说明:
    - map_types与columns一一对应，第i个列使用第i个映射类型
    - 使用get_value_type判断对应列的类型
    - 如果映射列为value类型，进行连续映射
    - 如果为category类型，使用枚举型映射
    - inRange中的范围会自动设定
    - 如果是枚举型，通过random_color_list生成随机颜色列表

In [40]:
df

   x  y  z  w
a  1  2  3  a
b  4  5  6  b
c  7  8  9  c

In [44]:
df.reset_index()

  index  x  y  z  w
0     a  1  2  3  a
1     b  4  5  6  b
2     c  7  8  9  c

In [41]:
vm1

In [61]:
config0=create_visual_map(df.reset_index(),"color",3)

In [62]:
config0

{'visualMap': [{'type': 'continuous',
   'dimension': 3,
   'min': 3.0,
   'max': 9.0,
   'inRange': {'color': ['#50a3ba', '#eac736', '#d94e5d']}}]}

In [63]:
vm1.rect_plot("scatter",0,2,config0).render_notebook()

In [65]:
config0=create_visual_map(df.reset_index(),["symbolSize","color"],[2,3])
vm1.rect_plot("scatter",0,2,config0).render_notebook()

### classwork3

* 用散点图研究销量前50店铺各个维度的关系

In [70]:
nick50=nick_tz.head(50)
nick_tz.head(5)

           price_mean    gmv_sum      gmv_mean  sales_mean  sales_sum  size
nick
意尔康皮鞋旗舰店   485.712803  3558446.0  12312.961938   47.833910      13824   289
意尔康男鞋旗舰店   680.812081   792685.0   5320.033557   17.953020       2675   149
意尔康品牌店     271.461538   114452.0   1760.800000    7.661538        498    65
乙方乙方88888  164.666667    88144.0   9793.777778   60.333333        543     9
吸引力xl      152.000000    43870.0   8774.000000   59.000000        295     5

In [71]:
p6_kvm=pc.k_vm(nick50)

In [72]:
p6_kvm.rect_plot("scatter",1,4).render_notebook()

In [73]:
config0=create_visual_map(nick50.reset_index(),["symbolSize","color"],[5,6])
config0

{'visualMap': [{'type': 'continuous',
   'dimension': 5,
   'min': 19.0,
   'max': 13824.0,
   'inRange': {'symbolSize': [10, 30]}},
  {'type': 'continuous',
   'dimension': 6,
   'min': 1.0,
   'max': 289.0,
   'inRange': {'color': ['#50a3ba', '#eac736', '#d94e5d']},
   'show': False}]}

In [77]:
nick50_p=p6_kvm.rect_plot("scatter",1,4,config0)
nick50_p.render_notebook()

In [78]:
nick50_p.patch_option("增加一个提示框，显示对应第0列的值以及进行visualMap映射的那几列的值",verbose=True)
nick50_p.render_notebook()

AI Model Response:
{
    "tooltip": {
        "trigger": "item",
        "formatter": "JsCode:function(params) { var data = params.data; var visualMapData1 = data[5]; var visualMapData2 = data[6]; return data[0] + '<br/>sales_sum: ' + visualMapData1 + '<br/>size: ' + visualMapData2; }"
    }
}