# pancharts —geo 地理坐标可视化

基于pyecharts的可视化工具，配置语法与原生的echarts保持一致，完全兼容pandas的数据结构

老师自己开发！

https://github.com/wisherg/pancharts

https://echarts.apache.org/zh/api.html#echarts

### 安装

pip install pancharts -i https://mirrors.aliyun.com/pypi/simple/

### 更新

* 更新前请先保存你的配置文件！

pip install --upgrade pancharts -i https://mirrors.aliyun.com/pypi/simple/

In [4]:
#pip install --upgrade pancharts -i https://mirrors.aliyun.com/pypi/simple/

In [3]:
import numpy as np
import pandas as pd
from pancharts import echat,pchat,k2_nv,k2_nv,k_v,km_nv,Pancharts,create_visual_map,gk_vm,gk_vm_globe,gk_vm_amap
import pancharts as pc

In [2]:
pc.__version__

'0.1.5'

In [2]:
#echat("帮我做一个柱状图示例")

## 内置agent的使用与全局配置

In [1]:
from pancharts.utils import get_config_file_path

config_path = get_config_file_path()
print(config_path)

d:\soft\anaconda\Lib\site-packages\pancharts\chart_config.py

## k_v的地理可视化

* map地图可视化的核心就是地点的名称要与地图上提供的名称匹配，否则图元会无法显示

In [4]:
province_list = ["湖南省","浙江省","安徽省","福建省","江西省","山东省"]
provice_data = pd.Series(np.random.randint(0, 100, size=len(province_list)), index=province_list)
print(provice_data)

湖南省    24
浙江省    35
安徽省    88
福建省    54
江西省    35
山东省    75
dtype: int32

In [5]:
province_plot=pc.k_v(provice_data)
province_plot.map("china",{"series":[{"label":False}]}).render_notebook()

## k_vm的geo地理坐标可视化

* 行索引需要是地点名称，前两列必须是经度和纬度

* 其他列是特征值，默认映射第三列的值为color，修改映射与create_visual_map类似，本质上图形函数就是调用它实现的

* geo地点不受母图限制，能提供更灵活的可视化

In [5]:
print(gk_vm.__doc__)

地理数据可视化类，用于可视化pandas中表示地理信息的数据。

主要功能：
    - 支持基于地理坐标的数据可视化
    - 自动将DataFrame转换为ECharts地理图表可接受的数据格式
    - 支持多种地理图表类型，包括2D和3D图表
    - 支持数据可视化映射（颜色、大小等）

数据格式要求：
    - DataFrame的索引为地理位置名称
    - 默认前两列数据为经纬度（longitude, latitude）
    - 后续列可以是其他数值型数据，用于可视化映射

支持的图表类型：
    - scatter: 地理散点图
    - escatter: 地理特效散点图
    - heatmap: 地理热力图
    - graph: 地理关系图（节点-边）
    - bar3d: 3D柱状图（基于geo3D）
    - line3d: 3D飞线图（基于geo3D）

参数：
    data: pandas DataFrame - 地理数据，索引为位置名称，前两列为经纬度
    map_type: str - 地图类型，如"china"、"world"等

用法示例：
    from pancharts import gk_vm
    import pandas as pd

    # 创建地理数据（索引为城市名，前两列为经纬度）
    data = pd.DataFrame({
        'lng': [116.4074, 121.4737, 104.0668],
        'lat': [39.9042, 31.2304, 30.5728],
        'value': [100, 200, 150]
    }, index=['北京', '上海', '成都'])

    # 创建地理可视化实例
    geo_chart = gk_vm(data, map_type='china')

    # 绘制散点图
    chart = geo_chart.scatter(dimension=2, visual_type='color')
    chart.render()

In [6]:
#把下面这个数据转化为数据框，name为索引,后面value分为四列，分别为经度、纬度、人口、收入
z=[
        {"name": "北京", "value": [116.46, 39.92, 800,90,"市"]},
        {"name": "上海", "value": [121.48, 31.22, 900,70,"市"]},
        {"name": "广州", "value": [113.23, 23.16, 700,50,"省"]},
        {"name": "深圳", "value": [114.07, 22.62, 600,40,"省"]},
        {"name": "成都", "value": [104.06, 30.67, 500,20,"省"]}
      ]
    
z1={'经度':[],'纬度':[],'人口':[],'收入':[],'类型':[]}
z1_index=[]
for i in z:
  z1['经度'].append(i['value'][0])
  z1['纬度'].append(i['value'][1])
  z1['人口'].append(i['value'][2])
  z1['收入'].append(i['value'][3])
  z1['类型'].append(i['value'][4])
  z1_index.append(i['name'])

geo_df=pd.DataFrame(z1,index=z1_index)
geo_df

        经度     纬度   人口  收入 类型
北京  116.46  39.92  800  90  市
上海  121.48  31.22  900  70  市
广州  113.23  23.16  700  50  省
深圳  114.07  22.62  600  40  省
成都  104.06  30.67  500  20  省

In [7]:
chinamap=gk_vm(geo_df,"china")
p1=chinamap.scatter()
p1.render_notebook()

In [5]:
p1=chinamap.escatter()
p1.render_notebook()

In [6]:
p1=chinamap.heatmap()
p1.render_notebook()

In [3]:
#p1=chinamap.bar3d()
#p1.render_notebook()

In [17]:
geo_df

        经度     纬度   人口  收入 类型
北京  116.46  39.92  800  90  市
上海  121.48  31.22  900  70  市
广州  113.23  23.16  700  50  省
深圳  114.07  22.62  600  40  省
成都  104.06  30.67  500  20  省

In [10]:
p1=chinamap.scatter(3,"symbolSize")
p1.render_notebook()

In [11]:
p1=chinamap.scatter([2,3],["color","symbolSize"])
p1.render_notebook()

## 高德地图api的注册与使用（国内地址）

https://lbs.amap.com/

单月150000次请求

* 国外开源地图api的，国内外地址皆可搜，就是慢一点

* 两种应用key Web端与Web服务 前者用来可视化地图，后者用来获取地理坐标   


https://opencagedata.com/

 2,500 API requests/day

In [4]:
from pancharts.utils import geocode_amap,geocode_opencage

In [8]:
geocode_amap("美国")

[geocode_amap错误] 高德地图API返回失败: status=0, info=ENGINE_RESPONSE_DATA_ERROR
[geocode_amap错误] 高德地图API返回失败: status=0, info=ENGINE_RESPONSE_DATA_ERROR
[geocode_amap错误] 高德地图API返回失败: status=0, info=ENGINE_RESPONSE_DATA_ERROR

(None, None)

In [7]:
geocode_amap(['上饶', '东莞', '中山'])

([117.943064, 113.751884, 113.392517], [28.45513, 23.021016, 22.517024])

In [9]:
geocode_opencage("美国")

(-100.445882, 39.7837304)

## classwork 1

* 完成高德地图的注册，获取地图密钥，有兴趣可以再完成opencage的地图秘钥注册

* 完成男鞋数据的导入，求每个城市男鞋的商品数量

* 查询城市对应的经度和纬度

* 完成城市商品数的geo地图可视化

In [5]:
a=pd.read_csv(r"e:\shoes.csv")
a["sales"]=a.sales.str.replace("人付款","").astype(int)
a["gmv"]=a.sales*a.price

In [13]:
a.head(1)

,_id.$oid,info.上市年份季节,info.上市时间,info.产品名称,info.低帮鞋品名,info.功能,info.吊牌价,info.品牌,info.图案,info.场合,...,info.颜色分类,info.风格,itemid,location,nick,price,sales,title,url,gmv
0,5aa77041be9b0338dc1faab4,2018年春季,NaN,NaN,商务休闲鞋,轻质,NaN,YEARCON/意尔康,纯色,日常,...,黑色土黄,商务,562121114807,浙江 丽水,意尔康皮鞋旗舰店,269.0,1583,意尔康男鞋2018春季新款英伦真皮商务休闲皮鞋青年男士皮鞋子男潮,http://detail.tmall.com/item.htm?id=5621211148...,425827.0

In [6]:
a.location.str.split(" ",expand=True)[1]

0         丽水
1         丽水
2         温州
3         温州
4         丽水
        ...
4982      泉州
4983      东莞
4984      泉州
4985      泉州
4986    None
Name: 1, Length: 4987, dtype: object

In [7]:
city=a.location.str.split(" ",expand=True)[1]

In [8]:
city_size=a.groupby(city).size()

In [10]:
citysize10=city_size.sort_values(ascending=False)[0:10]

In [20]:
#city_size.index.tolist()

In [22]:
#city_size.index.tolist()

In [9]:
lnglat=geocode_amap(city_size.index.tolist())

In [11]:
#lnglat

In [18]:
#lnglat

In [ ]:
pd.DataFrame({'city':city_size.index.tolist(),'lng':lnglat[0],'lat':lnglat[1],'size':city_size.values}).set_index('city')

In [15]:
city_shoes=pd.DataFrame({'city':citysize10.index.tolist(),'lng':lnglat[0],'lat':lnglat[1],'size':citysize10.values})
city_shoes.set_index('city',inplace=True)
city_shoes.head()

             lng        lat  size
city
温州    120.699279  27.993849  1275
丽水    119.923249  28.467694   938
泉州    118.675724  24.874452   798
郑州    113.625351  34.746303   393
广州    113.264499  23.130061   264

In [17]:
city_s_p=gk_vm(city_shoes,"china")
city_s_p_s=city_s_p.scatter()
#city_s_p_s.render_notebook()

In [ ]:
#city_s_p_s=city_s_p.bar3d()
#city_s_p_s.render_notebook()

:

## 地图上的网络

### classwork 2

* graph #默认显示所有点
* line3d #默认不显示点

In [21]:
egdes=[["温州","郑州"],["温州","广州"]]
#city_s_p.graph(egdes).render_notebook()

In [23]:
egdes=[["温州","郑州"],["温州","广州"]]
z1=city_s_p.line3d(egdes)
#z1.render_notebook()

In [27]:
#z1.option

In [2]:
z1.patch_option("让边变粗一些")
#z1.render_notebook()

NameError: name 'z1' is not defined

## 基于高德地图的地理坐标可视化

* 暂时只能在独立页面上显示，不能在notebook中直接显示

In [8]:
print(gk_vm_amap.__doc__)

高德地图地理数据可视化类，用于通过高德地图API进行地理信息可视化。

主要功能：
    - 支持基于高德地图的地理坐标数据可视化
    - 自动通过高德地图API获取地图中心点
    - 支持多种地理图表类型
    - 支持数据可视化映射（颜色、大小等）

数据格式要求：
    - DataFrame的索引为地理位置名称
    - 默认前两列数据为经纬度（longitude, latitude）
    - 后续列可以是其他数值型数据，用于可视化映射

支持的图表类型：
    - scatter: 散点图
    - effectScatter: 涟漪高亮散点图
    - heatmap: 热力图
    - graph: 关系网络图
    - lines: 飞线图/迁徙图

参数：
    data: pandas DataFrame - 地理数据，索引为位置名称，前两列为经纬度
    map_type: str - 地址名称，用于获取地图中心点（如"北京市"、"上海市"等）

用法示例：
    from pancharts import gk_vm_amap
    import pandas as pd

    # 创建地理数据（索引为城市名，前两列为经纬度）
    data = pd.DataFrame({
        'lng': [116.4074, 121.4737, 104.0668],
        'lat': [39.9042, 31.2304, 30.5728],
        'value': [100, 200, 150]
    }, index=['北京', '上海', '成都'])

    # 创建高德地图可视化实例（以"北京市"为中心）
    amap_chart = gk_vm_amap(data, map_type='北京市')

    # 绘制散点图
    chart = amap_chart.scatter(dimension=2, visual_type='color')
    chart.render()

In [28]:
from pancharts import gk_vm_amap
import pandas as pd

# 创建地理数据
data = pd.DataFrame({
    'lng': [116.4074, 121.4737, 104.0668],
    'lat': [39.9042, 31.2304, 30.5728],
    'value': [100, 200, 150]
}, index=['北京', '上海', '成都'])

# 创建高德地图可视化实例（以"北京市"为中心）
amap_chart = gk_vm_amap(data)

# 绘制散点图
chart = amap_chart.heatmap()
chart.render()

'index.html'

In [29]:
data

         lng      lat  value
北京  116.4074  39.9042    100
上海  121.4737  31.2304    200
成都  104.0668  30.5728    150

### 重要配置

* 官方内置样式：normal(标准)、light(浅灰)、dark(暗黑)

* // 1. 中心点：默认会计算经纬度值的中心点
  // 可以自定义其他地址名称，例如："上海"、"广州"等

  // 2. 初始缩放级别（2-18，数值越大越近）
  zoom: 10,

In [29]:
config={"init":{"width":"100%","height":"800px"},"amap":{"mapStyle": 'amap://styles/dark',"zoom":7}}
chart = amap_chart.scatter(config=config)
chart.render()

'index.html'

In [7]:
data

         lng      lat  value
北京  116.4074  39.9042    100
上海  121.4737  31.2304    200
成都  104.0668  30.5728    150

### classwork3 

* 完成城市销售额的地理坐标可视化

In [30]:
city_sales=a.groupby(city).sales.sum()

In [31]:
city_sales

1
上饶         0
东莞         0
中山         1
临沂         0
丽水     18084
九江         0
保定        43
南京        49
南平        87
南昌         1
厦门         2
台州         0
合肥         1
嘉兴         0
太原        12
宁德        59
宁波        41
安庆         7
宜春         0
宿迁         0
常州        32
广元         0
广州        39
徐州         1
恩施         0
成都        23
扬州       280
杭州       106
松原         0
武汉         3
汕头        17
沈阳        10
泉州       122
济南         5
深圳         2
温岭        13
温州      4372
湖州         2
潍坊         2
珠海         0
石家庄      153
绍兴         0
苏州         1
莱芜         1
衢州         0
襄阳         0
贵阳         0
连云港        0
邢台         0
郑州        44
金华         0
镇江         3
青岛         0
黄石         0
Name: sales, dtype: int64

In [32]:
city_shoes

             lng        lat  size
city
温州    120.699279  27.993849  1275
丽水    119.923249  28.467694   938
泉州    118.675724  24.874452   798
郑州    113.625351  34.746303   393
广州    113.264499  23.130061   264
宁德    119.547729  26.666222   126
湖州    120.086881  30.894178   118
杭州    120.209903  30.246566   107
扬州    119.412834  32.394404    92
石家庄   114.514976  38.042007    70

In [36]:
help(pd.concat)

Help on function concat in module pandas.core.reshape.concat:

concat(
    objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys: 'Iterable[Hashable] | None' = None,
    levels=None,
    names: 'list[HashableT] | None' = None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool | None' = None
) -> 'DataFrame | Series'
    Concatenate pandas objects along a particular axis.

    Allows optional set logic along the other axes.

    Can also add a layer of hierarchical indexing on the concatenation axis,
    which may be useful if the labels are the same (or overlapping) on
    the passed axis number.

    Parameters
    ----------
    objs : a sequence or mapping of Series or DataFrame objects
        If a mapping is passed, the sorted keys will be used as the `keys`
        argument, unless it is passed, in which case the values will be
        selected (see below). Any None objects will be dropped silently unless
        they are all None in which case a ValueError will be raised.
    axis : {0/'index', 1/'columns'}, default 0
        The axis to concatenate along.
    join : {'inner', 'outer'}, default 'outer'
        How to handle indexes on other axis (or axes).
    ignore_index : bool, default False
        If True, do not use the index values along the concatenation axis. The
        resulting axis will be labeled 0, ..., n - 1. This is useful if you are
        concatenating objects where the concatenation axis does not have
        meaningful indexing information. Note the index values on the other
        axes are still respected in the join.
    keys : sequence, default None
        If multiple levels passed, should contain tuples. Construct
        hierarchical index using the passed keys as the outermost level.
    levels : list of sequences, default None
        Specific levels (unique values) to use for constructing a
        MultiIndex. Otherwise they will be inferred from the keys.
    names : list, default None
        Names for the levels in the resulting hierarchical index.
    verify_integrity : bool, default False
        Check whether the new concatenated axis contains duplicates. This can
        be very expensive relative to the actual data concatenation.
    sort : bool, default False
        Sort non-concatenation axis if it is not already aligned. One exception to
        this is when the non-concatentation axis is a DatetimeIndex and join='outer'
        and the axis is not already aligned. In that case, the non-concatenation
        axis is always sorted lexicographically.
    copy : bool, default True
        If False, do not copy data unnecessarily.

    Returns
    -------
    object, type of objs
        When concatenating all ``Series`` along the index (axis=0), a
        ``Series`` is returned. When ``objs`` contains at least one
        ``DataFrame``, a ``DataFrame`` is returned. When concatenating along
        the columns (axis=1), a ``DataFrame`` is returned.

    See Also
    --------
    DataFrame.join : Join DataFrames using indexes.
    DataFrame.merge : Merge DataFrames by indexes or columns.

    Notes
    -----
    The keys, levels, and names arguments are all optional.

    A walkthrough of how this method fits in with other tools for combining
    pandas objects can be found `here
    <https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html>`__.

    It is not recommended to build DataFrames by adding single rows in a
    for loop. Build a list of rows and make a DataFrame in a single concat.

    Examples
    --------
    Combine two ``Series``.

    >>> s1 = pd.Series(['a', 'b'])
    >>> s2 = pd.Series(['c', 'd'])
    >>> pd.concat([s1, s2])
    0    a
    1    b
    0    c
    1    d
    dtype: object

    Clear the existing index and reset it in the result
    by setting the ``ignore_index`` option to ``True``.

    >>> pd.concat([s1, s2], ignore_index=True)
    0    a
    1    b
    2    c
    3    d
    dtype: object

    Add a hierarchical index at the outermost level of
    the data with the ``keys`` option.

    >>> pd.concat([s1, s2], keys=['s1', 's2'])
    s1  0    a
        1    b
    s2  0    c
        1    d
    dtype: object

    Label the index keys you create with the ``names`` option.

    >>> pd.concat([s1, s2], keys=['s1', 's2'],
    ...           names=['Series name', 'Row ID'])
    Series name  Row ID
    s1           0         a
                 1         b
    s2           0         c
                 1         d
    dtype: object

    Combine two ``DataFrame`` objects with identical columns.

    >>> df1 = pd.DataFrame([['a', 1], ['b', 2]],
    ...                    columns=['letter', 'number'])
    >>> df1
      letter  number
    0      a       1
    1      b       2
    >>> df2 = pd.DataFrame([['c', 3], ['d', 4]],
    ...                    columns=['letter', 'number'])
    >>> df2
      letter  number
    0      c       3
    1      d       4
    >>> pd.concat([df1, df2])
      letter  number
    0      a       1
    1      b       2
    0      c       3
    1      d       4

    Combine ``DataFrame`` objects with overlapping columns
    and return everything. Columns outside the intersection will
    be filled with ``NaN`` values.

    >>> df3 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
    ...                    columns=['letter', 'number', 'animal'])
    >>> df3
      letter  number animal
    0      c       3    cat
    1      d       4    dog
    >>> pd.concat([df1, df3], sort=False)
      letter  number animal
    0      a       1    NaN
    1      b       2    NaN
    0      c       3    cat
    1      d       4    dog

    Combine ``DataFrame`` objects with overlapping columns
    and return only those that are shared by passing ``inner`` to
    the ``join`` keyword argument.

    >>> pd.concat([df1, df3], join="inner")
      letter  number
    0      a       1
    1      b       2
    0      c       3
    1      d       4

    Combine ``DataFrame`` objects horizontally along the x axis by
    passing in ``axis=1``.

    >>> df4 = pd.DataFrame([['bird', 'polly'], ['monkey', 'george']],
    ...                    columns=['animal', 'name'])
    >>> pd.concat([df1, df4], axis=1)
      letter  number  animal    name
    0      a       1    bird   polly
    1      b       2  monkey  george

    Prevent the result from including duplicate index values with the
    ``verify_integrity`` option.

    >>> df5 = pd.DataFrame([1], index=['a'])
    >>> df5
       0
    a  1
    >>> df6 = pd.DataFrame([2], index=['a'])
    >>> df6
       0
    a  2
    >>> pd.concat([df5, df6], verify_integrity=True)
    Traceback (most recent call last):
        ...
    ValueError: Indexes have overlapping values: ['a']

    Append a single row to the end of a ``DataFrame`` object.

    >>> df7 = pd.DataFrame({'a': 1, 'b': 2}, index=[0])
    >>> df7
        a   b
    0   1   2
    >>> new_row = pd.Series({'a': 3, 'b': 4})
    >>> new_row
    a    3
    b    4
    dtype: int64
    >>> pd.concat([df7, new_row.to_frame().T], ignore_index=True)
        a   b
    0   1   2
    1   3   4

In [39]:
city_ss=pd.concat([city_shoes,city_sales],axis=1,join="inner")
city_ss.head()

           lng        lat  size  sales
温州  120.699279  27.993849  1275   4372
丽水  119.923249  28.467694   938  18084
泉州  118.675724  24.874452   798    122
郑州  113.625351  34.746303   393     44
广州  113.264499  23.130061   264     39

In [40]:
city_ss

            lng        lat  size  sales
温州   120.699279  27.993849  1275   4372
丽水   119.923249  28.467694   938  18084
泉州   118.675724  24.874452   798    122
郑州   113.625351  34.746303   393     44
广州   113.264499  23.130061   264     39
宁德   119.547729  26.666222   126     59
湖州   120.086881  30.894178   118      2
杭州   120.209903  30.246566   107    106
扬州   119.412834  32.394404    92    280
石家庄  114.514976  38.042007    70    153

In [41]:
amap_chart = gk_vm_amap(city_ss)
chart = amap_chart.scatter([2,3],["symbolSize","color"],config=config)
chart.render("amap_chart.html")

'amap_chart.html'

In [37]:
chart = amap_chart.heatmap()
chart.render()

'index.html'

In [42]:
egdes=[["温州","郑州"],["湖州","丽水"],["湖州","杭州"]]
chart = amap_chart.graph(egdes,config=config)
chart.render()

'index.html'

In [43]:
egdes=[["温州","郑州"],["湖州","丽水"],["湖州","杭州"]]
chart = amap_chart.lines(egdes,config=config)
chart.render()

'index.html'

## 基于地球的地理可视化

In [59]:
print(gk_vm_globe.__doc__)

Globe 地球可视化类，用于在三维地球表面上进行数据可视化。

主要功能：
    - 支持基于ECharts Globe组件的全球地理数据可视化
    - 提供多种地球渲染风格（基础、夜景、真实感、地形）
    - 支持数据可视化映射（颜色、大小等）

数据格式要求：
    - DataFrame的索引为地理位置名称
    - 前两列为经纬度（longitude, latitude）
    - 后续列可以是其他数值型数据，用于可视化映射

支持的globe类型：
    - 'basic': 基础地球配置，使用lambert着色
    - 'night': 带高度纹理和夜景图层的地球
    - 'realistic': 真实感渲染地球，使用PBR材质
    - 'terrain': 地形渲染地球，显示地形起伏

支持的图表类型：
    - scatter: 3D散点图
    - bar3d: 3D柱状图
    - lines3d: 3D飞线图/迁徙图

参数：
    data: pandas DataFrame - 地理数据，索引为位置名称，前两列为经纬度
    globe_type: str, optional - 地球类型，可选值为 'basic', 'night', 'realistic', 'terrain'，默认为 'basic'

用法示例：
    from pancharts import gk_vm_globe
    import pandas as pd

    # 创建地理数据（索引为城市名，前两列为经纬度）
    data = pd.DataFrame({
        'lng': [116.4074, 121.4737, 104.0668, -73.9857],
        'lat': [39.9042, 31.2304, 30.5728, 40.7484],
        'value': [100, 200, 150, 180]
    }, index=['北京', '上海', '成都', '纽约'])

    # 创建Globe可视化实例（使用夜景模式）
    globe_chart = gk_vm_globe(data, globe_type='night')

    # 绘制散点图
    chart = globe_chart.scatter(dimension=2, visual_type='color')
    chart.render()

In [50]:
# 创建地理数据
data = pd.DataFrame({
    'lng': [116.4074, 121.4737, 104.0668, -73.9857],
    'lat': [39.9042, 31.2304, 30.5728, 40.7484],
    'value': [100, 200, 150, 180]
}, index=['北京', '上海', '成都', '纽约'])

g_config ={"init":{"width":"100%","height":"800px"}}

# 创建Globe可视化实例（使用夜景模式）
globe_chart = gk_vm_globe(data, "realistic")

# 绘制散点图
chart = globe_chart.lines3d([('北京', '上海'), ('上海', '成都'), ('成都', '纽约')])
#chart.render_notebook()

## classwork 4

* 完成城市数据在地球上的散点图与柱状图

In [51]:
globe_chart = gk_vm_globe(city_ss, "basic")

In [53]:
chart=globe_chart.scatter()
#chart.render_notebook()

In [12]:
#chart=globe_chart.bar3d()
#chart.render_notebook()

In [80]:
chart.patch_option("去掉柱子上的label")

JSON解析失败
原始输出: {"series": [{"label": {"show": False}}]}

In [5]:
#chart.dmerge({"series": [{"label": {"show": False}}]})
#chart.render_notebook()